project:
  type: book

book:
  title: "Sample Size for Medical Research with R"
  subtitle: "A Quick Guide Cookbook"
  author: "Kittipos Sirivongrungson"
  date: "12/17/2023"
  site-url: https://ss4medr.netlify.app
  repo-url: "https://github.com/Lightbridge-KS/ss4medr"
  chapters:
    - index.qmd
    - "contents/funda.qmd"
    - "contents/pwr.qmd"
    - part: "Group comparison"
      chapters: 
        - "contents/continuous.qmd"
    - part: "ML Studies"
      chapters: 
        - "contents/ml.qmd"
    - references.qmd

bibliography: assets/ref.bib

format:
  html:
    toc: true
    toc-depth: 5
    theme: 
      light: 
        - flatly
        #- custom.scss
      dark: 
        - darkly
    
execute:
  freeze: auto



